### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by imrn99** [imrn99/integraal#3]
# Integraal roadmap

this issue is a tracker for all  features that I consider(ed) to add, at some point, to the `integraal` crate; this only includes features related to the purpose of the crate, not all possible changes to this repository (e.g. having a better test coverage)

### Priority for the first "full" release

- Complete implementation for any combination of method / function descriptor / domain descriptor:
    - [x] rectangle
    - [x] trapezoid 
- Improve policy documentation & implementation consistency #11 
    - [x] #10
    - [x] update implementation to fit the doc
    - [x] Replace variant `ComputeMethod::Rectangle` by `ComputeMethod::RectangleLeft` & `ComputeMethod::RectangleRight`
- [x] Replace hardcoded `f64` usage by a generic `T: ...`: #13 
- [x] #16
- [x] #17
- [x] #19
- [x] #21
- [x] add a matrix in doc indicating which methods are implemented for each parameters

### Others

- [x] Complete the implementation for the Monte-Carlo method
- [x] ~Implement "execution back-ends" to handle multiple execution policy (e.g. sequential, parallel using `rayon`, parallel using `wgpu`)~ the `0.1.0` can be sequential only
- [x] Gate all additionnal computation methods / back-ends behind features; The result should be a fully additive list of features
- [x] ~Add support for multi-dimensional integral computations~ out of scope

## Updates

- 12/05: Organize features for a potential `0.1.0` release

**Comment by imrn99** [comment]
Last tasks before `0.1.0`
- [x] #40 
- [x] Make a feature list / release note
- [x] update readme
- [x] prepare a Rust scicomp article? / same as release note???
