### ISSUE TITLE
enh: improve overall integration

### ISSUE THREAD

**Issue by imrn99** [imrn99/integraal#7]
Collection of stuff to do:
- [x] exclude examples from test coverage analysis: #8 
- [x] use workspace to separate examples from the main crate: #8 
- [x] add a tracker template for issues? #9 
- [x] add an intermediate doc page for GH pages #9 
- [x] add a CHANGELOG file #9
